name: yappu-world-server-lambda-ci

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   uses: actions/checkout@v4

            -   name: Setup JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'corretto'
                    cache: gradle

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3

            -   name: Create .env file
                run: |
                    mkdir -p src/main/resources
                    echo "DISCORD_SERVER_ALERT_WEBHOOK=${{ secrets.DISCORD_SERVER_TEST_WEBHOOK }}" > src/main/resources/.env
                    cat src/main/resources/.env

            -   name: Compile and run test
                run: |
                    ./gradlew check 

            # Discord Notification
            -   name: CI Success Notification
                uses: sarisia/actions-status-discord@v1
                if: success()
                with:
                    title: ✅ Lambda CI 성공 ✅
                    webhook: ${{ secrets.DISCORD_SERVER_WEBHOOK }}
                    color: 0x00FF00
                    username: 페페훅

            -   name: CI Failure Notification
                uses: sarisia/actions-status-discord@v1
                if: failure()
                with:
                    title: ❗️Lambda CI 실패 ❗️
                    webhook: ${{ secrets.DISCORD_SERVER_WEBHOOK }}
                    color: 0xFF0000
                    username: 페페훅
